insert into tb_cassandra_artist(nm_artist, slug_artist, img_icon)
	values	('Florence And The Machine','florence-and-the-machine','https://i.ibb.co/zVhbxwg/florence-and-the-machine.jpg'),
			('Taylor Swift','taylor-swift','https://i.ibb.co/s3rWnqq/taylor-swift.jpg'),
            ('ABBA','abba','https://i.ibb.co/bP2f6ph/abba.jpg'),
            ('Adele','adele','https://i.ibb.co/CtQ7wK7/adele.jpg'),
            ('Ariana Grande','ariana-grande','https://i.ibb.co/h24MWkp/ariana-grande.jpg'),
            ('Avril Lavigne','avril-lavigne','https://i.ibb.co/w6JtDZd/avril-lavigne.jpg'),
            ('Beyoncé','beyonce','https://i.ibb.co/HdYG7fB/beyonce.jpg'),
            ('Billie Eilish','billie-eilish','https://i.ibb.co/S0ZCNz8/billie-eilish.jpg'),
            ('Britney Spears','britney-spears','https://i.ibb.co/4tqCSkY/britney-spears.jpg'),
            ('Calcinha Preta','calcinha-preta','https://i.ibb.co/3Fhj7fC/calcinha-preta.jpg'),
            ('Carly Rae Jepsen','carly-rae-jepsen','https://i.ibb.co/VNp5wbF/carly-rae-jepsen.jpg'),
            ('Cher','cher','https://i.ibb.co/Y3D9ctj/cher.jpg'),
            ('Demi Lovato','demi-lovato','https://i.ibb.co/80J8CkX/demi-lovato.jpg'),
            ('Dove Cameron','dove-cameron','https://i.ibb.co/5x7MCkP/dove-cameron.jpg'),
            ("Guns N' Roses",'guns-n-roses','https://i.ibb.co/3BvBK9F/guns-n-roses.jpg'),
            ('Harry Styles','harry-styles','https://i.ibb.co/JKt7Gpn/harry-styles.jpg'),
            ('Isabella Summers','isabella-summers','https://i.ibb.co/RYH7qQJ/isabella-summers.jpg'),
            ('Jessie J','jessie-j','https://i.ibb.co/vzVmzzY/jessie-j.jpg'),
            ('Kailee Morgue','kailee-morgue','https://i.ibb.co/ZgPDtCx/kailee-morgue.jpg'),
            ('Katy Perry','katy-perry','https://i.ibb.co/N1gMPBn/katy-perry.jpg'),
            ('Lady Gaga','lady-gaga','https://i.ibb.co/9wWSFdV/lady-gaga.jpg'),
            ('Lana Del Rey','lana-del-rey','https://i.ibb.co/CtVcFc7/lana-del-rey.jpg'),
            ('Madonna','madonna','https://i.ibb.co/85D0PcL/madonna.jpg'),
            ('Maite Perroni','maite-perroni','https://i.ibb.co/cTQ3yny/maite-perroni.jpg'),
            ('Mariah Carey','mariah-carey','https://i.ibb.co/qCKzGV9/mariah-carey.jpg'),
            ('Marina','marina','https://i.ibb.co/hV9Z8JR/marina.jpg'),
            ('Maysa','maysa','https://i.ibb.co/mbKBx0D/maysa.jpg'),
            ('Melanie Martinez','melanie-martinez','https://i.ibb.co/wMLNR9h/melanie-martinez.jpg'),
            ('Miley Cyrus','miley-cyrus','https://i.ibb.co/bKv6RCf/miley-cyrus.jpg'),
            ('Nirvana','nirvana','https://i.ibb.co/d2gFrmH/nirvana.jpg'),
            ('Pablo Vittar','pablo-vittar','https://i.ibb.co/9crQHjf/pablo-vittar.jpg'),
            ('Paramore','paramore','https://i.ibb.co/tMG3Wh5/paramore.jpg'),
            ('Pitty','pitty','https://i.ibb.co/YhHJ6Zr/pitty.jpg'),
            ('Rihanna','rihanna','https://i.ibb.co/pf34FTT/rihanna.jpg'),
            ('Rita Lee','rita-lee','https://i.ibb.co/CB6Gx5C/rita-lee.jpg'),
            ('ROSALÍA','rosalia','https://i.ibb.co/s3ytDtb/rosalia.jpg'),
            ('Selena Gomez','selena-gomez','https://i.ibb.co/pXctLGT/selena-gomez.jpg'),
            ('SIA','sia','https://i.ibb.co/17VSc72/sia.jpg'),
            ('Stevie Nicks','stevie-nicks','https://i.ibb.co/pnTzHxH/stevie-nicks.jpg'),
            ('The Weeknd','the-weeknd','https://i.ibb.co/MsM9TQS/the-weeknd.jpg'),
            ('Winona Oak','winona-oak','https://i.ibb.co/BLHVRvz/winona-oak.jpg'),
            ('Zendaya','zendaya','https://i.ibb.co/0fT3ycX/zendaya.jpg');





