insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','',''),
        ('','','','1','','','','','','');

/* LUNGS */
insert into tb_cassandra_product
(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
    values  
        ('1','2','100.00','1','2009-07-03','11.00','7.0','7.0','7.0','<p>Originalmente lan&ccedil;ado em 3 de julho de 2009, Lungs foi uma estreia imensa, passando 89 semanas no top 40 do Reino Unido. Foi selecionado para o Mercury Prize de 2009 e ganhou o &Aacute;lbum Brit&acirc;nico do Ano no Brit Awards em 2010.</p>'),
        ('1','5','150.00','1','2009-07-03','31.09','31.09','0.79','168.11','<p>Prensagem de LPs do Reino Unido. &Aacute;lbum de estreia de 2009 da banda brit&acirc;nica de alta qualidade fornecida por Florence Welch. Lungs, produzido por Paul Epworth, James Ford e Steve Mackay, &eacute; uma mistura inebriante de fragilidade delicada, humor negro e contos de fadas ao estilo de Tim Burton. Da favorita ao vivo &#39;You&#39;ve Got The Love&#39; &agrave; crua &#39;Girl With One Eye&#39; com um toque de Blues e &agrave; belamente dolorosa &#39;Between Two Lungs&#39;, o &aacute;lbum est&aacute; repleto de agradar ao p&uacute;blico. Tamb&eacute;m com faixas novas como o novo single &#39;Rabbit Heart (Raise It Up)&#39;, &#39;Drumming&#39; - com sua densidade &eacute;pica, o terrivelmente brilhante &#39;Howl&#39; e &#39;Hurricane Drunk&#39; com seus encantos paradoxais de desgosto, amor e perda, Lungs promete para nos deixar querendo mais da insanamente cativante Florence Welch. Universal. 2009.</p>'),
        ('2','1','65.00','1', '2010-10-03','15.39','22.3','0.99','101.77','<p>Prensagem de LPs do Reino Unido. &Aacute;lbum de estreia de 2009 da banda brit&acirc;nica de alta qualidade fornecida por Florence Welch. Lungs, produzido por Paul Epworth, James Ford e Steve Mackay, &eacute; uma mistura inebriante de fragilidade delicada, humor negro e contos de fadas ao estilo de Tim Burton. Da favorita ao vivo &#39;You&#39;ve Got The Love&#39; &agrave; crua &#39;Girl With One Eye&#39; com um toque de Blues e &agrave; belamente dolorosa &#39;Between Two Lungs&#39;, o &aacute;lbum est&aacute; repleto de agradar ao p&uacute;blico. Tamb&eacute;m com faixas novas como o novo single &#39;Rabbit Heart (Raise It Up)&#39;, &#39;Drumming&#39; - com sua densidade &eacute;pica, o terrivelmente brilhante &#39;Howl&#39; e &#39;Hurricane Drunk&#39; com seus encantos paradoxais de desgosto, amor e perda, Lungs promete para nos deixar querendo mais da insanamente cativante Florence Welch. Universal. 2009.</p>'),
        ('3','3','254.90','1','2019-07-03','33.32','33.45','4.39','1.82','<p>Esta edi&ccedil;&atilde;o de 10&ordm; anivers&aacute;rio &eacute; uma caixa deluxe encadernada em tecido com o &aacute;lbum Lungs original em vinil colorido e um LP de material b&ocirc;nus, escolhido a dedo por Florence Welch e nunca antes dispon&iacute;vel em vinil. Este material inclui tr&ecirc;s faixas demo in&eacute;ditas, uma rara vers&atilde;o ac&uacute;stica de &#39;My Boy Builds Coffins&#39;, um cover de &#39;Oh! Darling&#39; Live at Abbey Road e v&aacute;rios lados B e raridades. Tamb&eacute;m est&atilde;o inclu&iacute;dos na caixa cart&otilde;es postais e encartes, mostrando as letras do &aacute;lbum.</p>');

/* CEREMONIALS */
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
    values  
        ('4','1','46.90','1','2014-10-28','15.39','22.3','0.99','101.77','<p>CD. 2011 segundo &aacute;lbum da banda brit&acirc;nica liderada pela cantora/compositora Florence Welch. Cerimonials &eacute; um registro impressionantemente realizado por uma artista oscilando no topo de seu jogo, um testemunho extraordin&aacute;rio do que Florence chama de &quot;meu maximalismo incorrig&iacute;vel&quot;. O positivismo epif&acirc;nico pulsante do &#39;Spectrum&#39;; a majestade galopante de &#39;All This And Heaven Too&#39; e &#39;Shake It Out&#39;; os triunfantes gritos de batalha emocionais de &#39;No Light No Light&#39; e &#39;Heartlines&#39;. Passe um pouco de tempo com Cerimoniais e o que mais o impressiona &eacute; a aparente confian&ccedil;a de sua execu&ccedil;&atilde;o. Gravado com sua banda completa durante cinco semanas neste ver&atilde;o no lend&aacute;rio Studio 3 de Abbey Road, Ceremonials &eacute; outro produto de sua longa colabora&ccedil;&atilde;o com o produtor Paul Epworth. Juntos, eles criaram uma vis&atilde;o pop-art expansiva que pode ser cativantemente terna e ainda frequentemente voar para lugares onde pode sobrecarregar os sentidos como uma onda emotiva.</p>'),
        ('4','5','170.90','0','2016-10-28','30.91','31.19','0.71','235.87','<p>Prensagem de vinil LP. 2011 segundo &aacute;lbum da banda brit&acirc;nica liderada pela cantora/compositora Florence Welch. Cerimonials &eacute; um registro impressionantemente realizado por uma artista oscilando no topo de seu jogo, um testemunho extraordin&aacute;rio do que Florence chama de &quot;meu maximalismo incorrig&iacute;vel&quot;. O positivismo epif&acirc;nico pulsante do &#39;Spectrum&#39;; a majestade galopante de &#39;All This And Heaven Too&#39; e &#39;Shake It Out&#39;; os triunfantes gritos de batalha emocionais de &#39;No Light No Light&#39; e &#39;Heartlines&#39;. Passe um pouco de tempo com Cerimoniais e o que mais o impressiona &eacute; a aparente confian&ccedil;a de sua execu&ccedil;&atilde;o. Gravado com sua banda completa durante cinco semanas neste ver&atilde;o no lend&aacute;rio Studio 3 de Abbey Road, Ceremonials &eacute; outro produto de sua longa colabora&ccedil;&atilde;o com o produtor Paul Epworth. Juntos, eles criaram uma vis&atilde;o pop-art expansiva que pode ser cativantemente terna e ainda frequentemente voar para lugares onde pode sobrecarregar os sentidos como uma onda emotiva.</p>');

/* HBHBHB */
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
    values  
        ('5','1','40.80','0','2019-08-14','15.39','22.3','0.99','101.77','<p>&lsquo;How Big, How Blue, How Beautiful&rsquo; &eacute; o novo &aacute;lbum da artista musical multi-platina Florence + The Machine, indicada ao Brit e ao Grammy, produzida por Markus Dravs (Bj&ouml;rk, Arcade Fire, Coldplay).</p>'),
        ('5','2','120.80','1','2019-08-14','11.00','7.0','7.0','7.0','<p>&lsquo;How Big, How Blue, How Beautiful&rsquo; &eacute; o novo &aacute;lbum da artista musical multi-platina Florence + The Machine, indicada ao Brit e ao Grammy, produzida por Markus Dravs (Bj&ouml;rk, Arcade Fire, Coldplay).</p>'),
        ('5','3','405.85','0','2021-08-14','33.32','33.45','4.39','1.82','<p>BOX</p>'),
        ('5','5','265.85','1','2021-08-14','30.91','31.19','0.71','235.87','<p>DISCO 1 LADO A<br /><br />1 Ship to Wreck 3:54<br />2 What Kind of Man 3:36<br /><br />DISCO 1 LADO B<br /><br />3 How Big, How Blue, How Beautiful 5:34<br />4 Queen of Peace 5:07<br />5 Various Storms &amp; Saints 4:09<br /><br />DISCO 2 LADO A<br /><br />6 Delilah 4:53<br />7 Long &amp; Lost 3:15<br />8 Caught 4:24<br /><br />DISCO 2 LADO B<br /><br />9 Third Eye 4:20<br />10 St Jude 3:45<br />11 Mother 5:49</p>'),
        ('6','1','45.90','1','2020-08-14','15.39','22.3','0.99','101.77','<p>&lsquo;How Big, How Blue, How Beautiful&rsquo; &eacute; o novo &aacute;lbum da artista musical multi-platina Florence + The Machine, indicada ao Brit e ao Grammy, produzida por Markus Dravs (Bj&ouml;rk, Arcade Fire, Coldplay).</p>'),
        ('7','5','250.98','0','2020-08-14','30.91','31.19','0.71','235.87','<p>DELUXE</p>');

/* HIGH AS HOPE */
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
    values 
        ('8','1','45.90','0','2018-06-29','15.39','22.3','0.99','101.77','<p>Tracklisting:</p><p>1. June</p><p>2. Hunger</p><p>3. South London Forever</p><p>4. Big God</p><p>5. Sky Full of Song</p><p>6. Grace</p><p>7. Patricia</p><p>8. 100 Years</p><p>9. The End of Love</p><p>10. No Choir</p>'),
        ('8','2','75.00','1','2018-06-29','11.00','7.0','7.0','7.0','<p>Tracklisting:</p><p>1. June</p><p>2. Hunger</p><p>3. South London Forever</p><p>4. Big God</p><p>5. Sky Full of Song</p><p>6. Grace</p><p>7. Patricia</p><p>8. 100 Years</p><p>9. The End of Love</p><p>10. No Choir</p>'),
        ('8','5','180.80','1','2018-06-29','30.91','31.19','0.71','235.87','<p>Tracklisting:</p><p>1. June</p><p>2. Hunger</p><p>3. South London Forever</p><p>4. Big God</p><p>5. Sky Full of Song</p><p>6. Grace</p><p>7. Patricia</p><p>8. 100 Years</p><p>9. The End of Love</p><p>10. No Choir</p>');

/* DANCE FEVER */
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('9','1','35.90','1','2022-05-13','12.0','12.0','7.50','120.0','<p>CD Florence + The Machine &ndash; Dance Fever</p><p>Mintpack Standard CD (Mint pack digi sleeve and CD Poster)</p><p>Repert&oacute;rio do CD: 1. King 2. Free 3. Choreomania 4. Back In Town 5. Girls Against God 6. Dream Girl Evil 7. Prayer Factory 8. Cassandra 9. Heaven Is Here 9. Daffodil 11. My Love 12. Restraint 13. The Bomb 14. Morning Elvis</p>'),
        ('9','2','127.42','1','2022-05-13','11.00','7.0','7.0','7.0','<p>Cassete Florence + The Machine - Dance Fever (Exclusive / Cassette 1) - Importado</p><p>Repert&oacute;rio do cassete:</p><p>Lado A: 1. King 2. Free 3. Choreomania 4. Back in Town 5. Girls Against God 6. Dream Girl Evil</p><p>Lado B: 1. Prayer Factor 2. Cassandra 3. Heaven is Here 4. Daffodil 5. My Love 6. Restraint 7. The Bomb 8. Morning Elvis</p>'),
        ('9','3','999.90','1','2022-05-13','2.0','31.30','31.30','700.00','<p>Box Vinil Florence + The Machine - Dance Fever (Boxset Deluxe 2LP) - Importado</p><p>- Caixa de eleva&ccedil;&atilde;o de 12&quot; x 12&quot; com folha de ouro com:<br />- 15 cart&otilde;es de m&uacute;sica com banda &#39;barriga&#39;<br />- Livro de letras soft pack de 92 p&aacute;ginas<br />- Retire o p&ocirc;ster frente e verso<br />- Vinil preto com capa tripla, interior impresso, lista de faixas de luxo</p>'),
        ('9','5','329.90','1','2022-05-13','1.0','31.30','31.30','420.0','<p>Standard Black (Standard track-listing, double vinyl, gatefold, printed inners, etching on 4th side)</p><p>Repert&oacute;rio dos LPs:</p><p>Side I: 1. King. 2. Free. 3. Choreomania. 4. Back In Town.</p><p>Side II: 1. Girls Against God. 2. Dream Girl Evil. 3. Prayer Factory. 4. Cassandra. 5. Heaven Is Here.</p><p>Side III: 1. Daffodil. 2. My Love. 3. Restraint. 4. The Bomb. 5. Morning Elvis</p>'),
        ('10','1','35.90','0','2022-05-13','12.0','12.0','7.50','120.0','<p>CD Florence + The Machine &ndash; Dance Fever</p><p>Mintpack Standard CD (Mint pack digi sleeve and CD Poster)</p><p>Repert&oacute;rio do CD: 1. King 2. Free 3. Choreomania 4. Back In Town 5. Girls Against God 6. Dream Girl Evil 7. Prayer Factory 8. Cassandra 9. Heaven Is Here 10. Daffodil 11. My Love 12. Restraint 13. The Bomb 14. Morning Elvis</p>'),
        ('10','2','127.42','1','2022-05-13','11.00','7.0','7.0','7.0','<p>Cassete Florence + The Machine - Dance Fever (Exclusive / Cassette 1) - Importado</p><p>Repert&oacute;rio do cassete:</p><p>Lado A: 1. King 2. Free 3. Choreomania 4. Back in Town 5. Girls Against God 6. Dream Girl Evil</p><p>Lado B: 1. Prayer Factor 2. Cassandra 3. Heaven is Here 4. Daffodil 5. My Love 6. Restraint 7. The Bomb 8. Morning Elvis</p>'),
        ('11','5','999.90','0','2022-05-13','1.0','31.30','31.30','420.0','<p>DELUXE</p>'),
        ('12','5','380.44','1','2022-05-13','1.0','31.30','31.30','420.0','<p>Observe que o vinil inclui destaques das apresenta&ccedil;&otilde;es completas no Madison Square Garden.</p><p>LP1 Side 1:<br />1 Heaven Is Here - Live At Madison Square Garden<br />2 King - Live At Madison Square Garden<br />3 Ship To Wreck - Live At Madison Square Garden<br />4 Free - Live At Madison Square Garden<br />5 Daffodil - Live At Madison Square Garden<br /><br />LP1 Side 2:<br />1 Dog Days Are Over - Live At Madison Square Garden<br />2 Girls Against God - Live At Madison Square Garden<br />3 Dream Girl Evil - Live At Madison Square Garden<br />4 Cassandra - Live At Madison Square Garden<br />5 Morning Elvis - Live At Madison Square Garden<br /><br />LP2 Side 1:<br />1 June - Live At Madison Square Garden<br />2 Choreomania - Live At Madison Square Garden<br />3 Kiss With A Fist - Live At Madison Square Garden<br />4 Cosmic Love - Live At Madison Square Garden<br />5 My Love - Live At Madison Square Garden<br />6 Restraint - Live At Madison Square Garden<br /><br />LP2 Side 2:<br />1 The End Of Love - Live At Madison Square Garden<br />2 Never Let Me Go - Live At Madison Square Garden<br />3 Shake It Out - Live At Madison Square Garden<br />4 Rabbit Heart (Raise It Up) - Live At Madison Square Garden</p><p>&nbsp;</p>');


/* ABBA */
	insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('13','5','224.91','1','2022-04-11','1.0','31.30','31.30','420.0','<p>Vinil Abba - Ring Ring (Picture Vinyl - Edi&ccedil;&atilde;o limitada) - Importado</p><p>Lan&ccedil;ado primeiro na Su&eacute;cia em 26 de mar&ccedil;o de 1973, Ring Ring &eacute; o &aacute;lbum de estreia da banda pop sueca ABBA.</p><p>Repert&oacute;rio do LP: Lado A: 1. Ring Ring (Swedish Version) 2. Another Town, Another Train 3. Disillusion 4. People Need Love 5. I Saw It In The Mirror 6. Nina, Pretty Ballerina</p><p>Lado B: 1. Love Isn&#39;t Easy (But It Sure Is Hard Enough) 2. Me And Bobby And Bobby&#39;s Brother 3. He Is Your Brother 4. Ring Ring (English Version) 5. I Am Just A Girl 6. Rock&#39;N&#39;Roll Band</p>'),
        ('14','5','224.91','1','2022-07-03','1.0','31.30','31.30','420.0','<p>Vinil Abba - Waterloo (Picture Vinyl - Edi&ccedil;&atilde;o limitada) - Importado</p><p>Originalmente lan&ccedil;ado em 4 de mar&ccedil;o de 1974 na Su&eacute;cia, Waterloo &eacute; o segundo &aacute;lbum de est&uacute;dio da banda sueca ABBA.</p><p>Repert&oacute;rio do LP:</p><p>Lado A: 1. Waterloo (Swedish Version) 2. Sitting In The Palmtree 3. King Kong Song 4. Hasta Ma&ntilde;ana 5. My Mama Said 6. Dance (While The Music Still Goes On)</p><p>Lado B: 1. Honey, Honey 2. Watch Out 3. What About Livingstone 4. Gonna Sing You My Lovesong 5. Suzy-Hang-Around 6. Waterloo (English Version)</p>'),
        ('15','5','224.91','1','2020-03-24','1.0','31.30','31.30','420.0','<p>Vinil Abba - Arrival (Picture Vinyl - Edi&ccedil;&atilde;o limitada) - Importado</p><p>Lan&ccedil;ado em 11 de outubro de 1976, Arrival &eacute; um &aacute;lbum de est&uacute;dio da banda ABBA.</p><p>Repert&oacute;rio do LP:</p><p>Lado A: 1. When I Kissed The Teacher 2. Dancing Queen 3. My Love, My Life 4. Dum Dum Diddle 5. Knowing Me, Knowing You</p><p>Lado B: 1. Money, Money, Money 2. That&#39;s Me 3. Why Did It Have To Be Me 4. Tiger 5. Arrival</p>'),
        ('16','1','224.91','1','2020-03-24','15.39','22.3','0.99','101.77','<p>CD ABBA - Voyage (CD - Jewel Case replacement) - Importado.</p><p>Voyage &eacute; o primeiro &aacute;lbum de est&uacute;dio do ABBA em 40 anos.</p><p>Repert&oacute;rio:</p><p>1. I Still Have Faith In You</p><p>2. When You Danced With Me</p><p>3. Little Things</p><p>4. Dont Shut Me Down</p><p>5. Just A Notion</p><p>6. I Can Be That Woman</p><p>7. Keep An Eye On Dan</p><p>8. Bumble Bee</p><p>9. No Doubt About It</p><p>10. Ode To Freedom</p>'),
        ('16','5','296.91','1','2020-03-24','1.0','31.30','31.30','420.0','<p>VINIL ABBA - Voyage (Vers&atilde;o Exclusiva | Vinil Verde) - Importado</p><p>Voyage &eacute; o primeiro &aacute;lbum de est&uacute;dio do ABBA em 40 anos.</p><p>Vinil verde Edi&ccedil;&atilde;o Limitada exclusiva. Inclu&iacute; p&ocirc;ster exclusivo e cart&atilde;o postal.</p><p>Faixas:</p><p>1. I Still Have Faith In You</p><p>2. When You Danced With Me</p><p>3. Little Things</p><p>4. Dont Shut Me Down</p><p>5. Just A Notion</p><p>6. I Can Be That Woman</p><p>7. Keep An Eye On Dan</p><p>8. Bumble Bee</p><p>9. No Doubt About It</p><p>10. Ode To Freedom</p>');

/* SELENA GOMEZ */
	insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('17','1','33.92','1','2022-07-29','15.39','22.3','0.99','101.77','<p>CD Selena Gomez - Stars Dance.</p><p>Lan&ccedil;ado em 23 de Julho de 2013, Stars Dance &eacute; o &aacute;lbum de estreia em carreira solo da cantora e atriz estadunidense Selena Gomez, sendo tamb&eacute;m o quarto &aacute;lbum de sua carreira.</p><p>Em sua primeira semana, o &aacute;lbum vendeu mais de 97.000 mil c&oacute;pias nos Estados Unidos, e consequentemente lhe fez estrear pela primeira vez no topo da Billboard 200. O disco rendeu dois singles: Come &amp; Get It, o primeiro, obteve &ecirc;xito comercial, sendo a primeira can&ccedil;&atilde;o de Gomez a entrar no top dez da Billboard Hot 100, ao atingir a 6&deg; posi&ccedil;&atilde;o.</p><p>Repert&oacute;rio do CD:</p><p>1. Birthday</p><p>2. Slow Down</p><p>3. Stars Dance</p><p>4. Like a Champion</p><p>5. Come &amp; Get It</p><p>6. Forget Forever</p><p>7. Save the Day</p><p>8. B.E.A.T.</p><p>9. Write Your Name</p><p>10. Undercover</p><p>11. Love Will Remember</p>'),
        ('18','1','33.92','0','2022-08-29','15.39','22.3','0.99','101.77','<p>Selena Gomez For You - CD Pop Traz o quarto &aacute;lbum da cantora americana, Selena Gomez. Lan&ccedil;ado em Novembro de 2014, apresenta 15 faixas, onde podemos encontrar os maiores sucessos da cantora como: Come &amp; Get It,Slow Down, Do It, al&eacute;m do novo single da cantora, The Heart Wants What It Wants e muito mais. Voc&ecirc; n&atilde;o pode deixar de conferir este CD indispens&aacute;vel para os amantes da m&uacute;sica, especialmente aos f&atilde;s de Selena Gomez, juntamente com o melhor do Pop<br /><br />Faixas<br />1. The Heart Wants What It Wants<br />2. Come &amp; Get It<br />3. Love You Like A Love Song<br />4. Tell Me Something I Don&#39;t Know<br />5. Who Says 06. My Dilemma 2.0<br />7. Round &amp; Round<br />8. Forget Forever - Boy Lightning Remix<br />9. Slow Down<br />10. A Year Without Rain - Dave Aud&eacute; Radio Remix<br />11. Naturally - Dave Aud&eacute; Radio Remix<br />12. M&aacute;s (More - Spanish Version)<br />13. Bidi Bidi Bom Bom<br />14. Falling Down<br />15. Do It</p>'),
        ('19','1','34.94','1','2022-09-02','15.39','22.3','0.99','101.77','<p>A imprensa tamb&eacute;m elogiou a nova dire&ccedil;&atilde;o de Gomez. Chamando &quot;Good For You&quot; de &quot;uma entrada sensual&quot;, a revista People diz que Gomez &quot;acertou seu passo&quot;, enquanto a Entertainment Weekly a chama de &quot;uma das m&uacute;sicas mais cintilantes deste ver&atilde;o&quot;. A Rolling Stone incluiu &quot;Good For You&quot; em sua lista das &quot;25 melhores m&uacute;sicas de 2015 at&eacute; agora&quot;. O v&iacute;deo, dirigido por Sophie Muller, conquistou mais de 100 milh&otilde;es de visualiza&ccedil;&otilde;es no Vevo.</p>'),
        ('20','5','258.91','1','2020-11-24','1.0','31.30','31.30','420.0','<p>VINIL Selena Gomez - Rare (Standard Vinyl) - Importado.</p><p>A cantora, letrista, atriz, empres&aacute;ria, produtora, estilista e dubladora multitalentosa Selena Gomez apresenta seu terceiro &aacute;lbum solo de est&uacute;dio, &quot;Rare&quot;. Lan&ccedil;ado em 10/01/2020, o t&atilde;o aguardado disco &#39;Rare&#39; representa uma vis&atilde;o da minha jornada de cura e crescimento.</p><p>&Eacute; de longe o trabalho que mais me orgulha at&eacute; hoje&quot;, diz Selena. O &aacute;lbum inclui a faixa que deu a Selena seu primeiro n&ordm;1 na parada Billboard Hot 100 da Billboard, &quot;Lose You To Love Me&quot;, m&uacute;sica da carreira da artista que mais r&aacute;pido recebeu o Certificado de Platina, al&eacute;m de aparecer em diversas listas de cr&iacute;ticos como uma das melhores m&uacute;sicas de 2019. O novo disco inclui tamb&eacute;m o hit &quot;Look At Her Now&quot; e a faixa-t&iacute;tulo, &quot;Rare&quot;.</p><p>Repert&oacute;rio do LP:</p><p>1. Rare</p><p>2. Dance Again</p><p>3. Look At Her Now</p><p>4. Lose You To Love Me</p><p>5. Ring</p><p>6. Vulnerable</p><p>7. People You Know</p><p>8. Let Me Get Me</p><p>9. Crowded Room (feat. 6LACK)</p><p>10. Kinda Crazy</p><p>11. Fun 12. Cut You Off</p><p>13. A Sweeter Place (feat. Kid Cudi)</p><p>&nbsp;</p><p>Todas as fotos e perspectivas contidas neste material s&atilde;o meramente ilustrativas, podendo sofrer altera&ccedil;&otilde;es, inclusive quanto &agrave; cor, tom, forma, textura e tamanho.</p>'),
        ('21','1','33.92','1','2021-10-23','15.39','22.3','0.99','101.77','<p>CD Selena Gomez - Rare - Deluxe.</p><p>A cantora, letrista, atriz, empres&aacute;ria, produtora, estilista e dubladora multitalentosa Selena Gomez apresenta seu terceiro &aacute;lbum solo de est&uacute;dio, &quot;Rare&quot;.</p><p>O t&atilde;o aguardado disco traz 18 faixas na vers&atilde;o Deluxe e participa&ccedil;&otilde;es especiais de 6LACK e Kid Cudi. &#39;Rare&#39; representa uma vis&atilde;o da minha jornada de cura e crescimento. &Eacute; de longe o trabalho que mais me orgulha at&eacute; hoje&quot;, diz Selena. O &aacute;lbum inclui a faixa que deu a Selena seu primeiro n&ordm;1 na parada Billboard Hot 100 da Billboard, &quot;Lose You To Love Me&quot;, m&uacute;sica da carreira da artista que mais r&aacute;pido recebeu o Certificado de Platina, al&eacute;m de aparecer em diversas listas de cr&iacute;ticos como uma das melhores m&uacute;sicas de 2019. O novo disco inclui tamb&eacute;m o hit &quot;Look At Her Now&quot; e a faixa-t&iacute;tulo, &quot;Rare&quot;.</p><p>Repert&oacute;rio do CD:</p><p>1. Rare</p><p>2. Dance Again</p><p>3. Look At Her Now</p><p>4. Lose You To Love Me</p><p>5. Ring 6. Vulnerable</p><p>7. People You Know</p><p>8. Let Me Get Me</p><p>9. Crowded Room</p><p>10. Kinda Crazy</p><p>11. Fun</p><p>12. Cut You Off</p><p>13. A Sweeter Place</p><p>14. Bad Liar</p><p>15. Fetish</p><p>16. It Ain&#39;t Me</p><p>17. Back To You</p><p>18. Wolves</p>'),
        ('22','1','33.92','1','2022-10-23','15.39','22.3','0.99','101.77','<p>CD Selena Gomez - Revelaci&oacute;n - Vers&atilde;o Standard.</p><p>Lan&ccedil;ado em 12 de mar&ccedil;o de 2021, Revelaci&oacute;n &eacute; um CD da cantora Selena Gomez, em l&iacute;ngua espanhola.</p><p>Repert&oacute;rio do CD: 1. De Una Vez 2. Buscando Amor 3. Baila Conmigo (with Raul Alejandro) 4. D&aacute;melo To&rsquo; (feat. Myke Towers) 5. Vicio 6. Adi&oacute;s 7. Selfish Love (with DJ Snake)</p>'),
        ('22','3','732.98','1','2022-10-23','2.0','31.30','31.30','700.00','<p>CD Selena Gomez - Revelaci&oacute;n Box Set (Limited Edition) - Importado</p><p>Lan&ccedil;ado em 12 de mar&ccedil;o de 2021, Revelaci&oacute;n &eacute; um CD da cantora Selena Gomez, em l&iacute;ngua espanhola.</p><p>Repert&oacute;rio do CD: 1. De Una Vez 2. Buscando Amor 3. Baila Conmigo (with Raul Alejandro) 4. D&aacute;melo To&rsquo; (feat. Myke Towers) 5. Vicio 6. Adi&oacute;s 7. Selfish Love (with DJ Snake)</p><p>Inclui:</p><p>CD EP em uma capa especial</p><p>Poster 20 P&aacute;ginas mini livro com fotos, cr&eacute;ditos, letras</p><p>4 Litogravuras</p>'),
        ('22','5','258.91','1','2022-11-24','1.0','31.30','31.30','420.0','<p>VINIL Selena Gomez - Revelaci&oacute;n Vers&atilde;o Standard - Importado</p><p>Repert&oacute;rio do LP: 1. De Una Vez 2. Buscando Amor 3. Baila Conmigo 4. D&aacute;melo To&#39; (Feat. Myke Towers) 5. Vicio 6. Adi&oacute;s 7. Selfish Love (With DJ Snake)</p><p>**todas as perspectivas contidas neste material s&atilde;o meramente ilustrativas, podendo sofrer altera&ccedil;&otilde;es, inclusive quanto &agrave; cor, forma, textura e tamanho.</p>'),
        ('23','5','258.91','1','2022-11-24','1.0','31.30','31.30','420.0','<p>VINIL Selena Gomez - Revelaci&oacute;n Vers&atilde;o Deluxe Vers&atilde;o Deluxe Exclusiva UMusic Store - Inclu&iacute; P&ocirc;ster e Capa Alternativa</p><p>Repert&oacute;rio do LP: 1. De Una Vez 2. Buscando Amor 3. Baila Conmigo 4. D&aacute;melo To&#39; (Feat. Myke Towers) 5. Vicio 6. Adi&oacute;s 7. Selfish Love (With DJ Snake)</p><p>**todas as perspectivas contidas neste material s&atilde;o meramente ilustrativas, podendo sofrer altera&ccedil;&otilde;es, inclusive quanto &agrave; cor, forma, textura e tamanho.</p>');

/*MARIAH CAREY*/
	insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('24','5','413.91','1','2020-11-24','15.39','22.3','0.99','101.77','<p>Vinil Duplo Mariah Carey - Charmbracelet (2LP) - Importado</p><p>Repert&oacute;rio dos LPs:</p><p>Disco 1 lado A: 1. Through the Rain 2. Boy (I Need You) (ft. Cam&#39;ron) 3. The One 4. Yours</p><p>Disco 1 lado B: 5. You Got Me (ft. Jay-Z and Freeway) 6. I Only Wanted 7. Clown</p><p>Disco 2 lado A: 8. My Saving Grace 9. You Had Your Chance 10. Lullaby 11. Irresistible (West Side Connection)</p><p>Disco 2 lado B: 12. Subtle Invitation 13. Bringin&#39; on the Heartbreak 14. Sunflowers for Alfred Roy 15. Through the Rain (Remix) (ft. Kelly Price and Joe)</p>'),
        ('25','5','341.01','1','2020-11-24','15.39','22.3','0.99','101.77','<p>Vinil Duplo Mariah Carey - E=MC2 (2LP) - Importado</p><p>Repert&oacute;rio dos LPs:</p><p>Disco 1 lado A: 1. Migrate (ft. T-Pain) 2. Touch My Body 3. Cruise Control (ft. Damian Marley) 4. I Stay in Love</p><p>Disco 1 lado B: 5. Side Effects (ft. Young Jeezy) 6. I&#39;m That Chick 7. Love Story</p><p>Disco 2 lado A: 8. I&#39;ll Be Lovin&#39; U Long Time 9. Last Kiss 10. Thanx 4 Nothin&#39; 11. O.O.C.</p><p>Disco 2 lado B: 12. For the Record 13. Bye Bye 14. I Wish You Well</p>'),
        ('26','5','258.91','1','2020-11-24','15.39','22.3','0.99','101.77','<p>Vinil Duplo Mariah Carey - Memoirs Of An Imperfect Angel (2LP) - Importado</p><p>Repert&oacute;rio dos LPs:</p><p>Disco 1 lado A: 1. Betcha Gon&#39; Know (The Prologue) 2. Obsessed 3. H.A.T.E.U. 4. Candy Bling</p><p>Disco 1 lado B: 5. Ribbon 6. Inseparable 7. Standing O 8. It&#39;s a Wrap</p><p>Disco 2 lado A: 9. Up Out My Face 10. Up Out My Face (The Reprise) 11. More Than Just Friends 12. The Impossible 13. The Impossible (The Reprise)</p><p>Disco 2 lado B: 14. Angel (The Prelude) 15. Angels Cry 16. Languishing (The Interlude) 17. I Want to Know What Love Is</p>');

/*BILLIE EILISH*/
	insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('27','1','42.42','1','2020-10-21','15.39','22.3','0.99','101.77','<p>CD Billie Eilish - dont smile at me - Importado.</p><p>Lan&ccedil;ado em 11 de agosto de 2017, Don&#39;t Smile at Me &eacute; a estr&eacute;ia estendida da cantora e compositora americana Billie Eilish.</p><p>Cont&eacute;m v&aacute;rios de seus singles lan&ccedil;ados anteriormente, incluindo &quot;Ocean Eyes&quot;, &quot;Bellyache&quot;, &quot;Watch&quot;, &quot;COPYCAT&quot; e &quot;Idontwannabeyouanymore&quot;. Repert&oacute;rio do CD: 1. COPYCAT 2. Idontwannabeyouanymore 3. My boy 4. Watch 5. Party favor 6. Bellyache 7. Ocean eyes 8. Hostage 9. &amp;bum (with Vince Staples)</p>'),
        ('27','5','251.91','1','2020-10-21','1.0','31.30','31.30','420.0','<p>VINIL Billie Eilish - Dont Smile At Me - Importado - Vermelho - 33 RPM.</p><p>Don&#39;t Smile at Me &eacute; a estr&eacute;ia estendida da cantora e compositora americana Billie Eilish. Foi lan&ccedil;ado em 11 de agosto de 2017 pela Interscope Records, e cont&eacute;m v&aacute;rios de seus singles lan&ccedil;ados anteriormente, incluindo &quot;Ocean Eyes&quot;, &quot;Bellyache&quot;, &quot;Watch&quot;, &quot;COPYCAT&quot; e &quot;Idontwannabeyouanymore&quot;.</p><p>Repert&oacute;rio do LP:</p><p>Lado A: 1. Copycat 2. Idontwannabeyouanymore 3. My Boy 4. Watch</p><p>Lado B: 1. Party Favor 2. Bellyache 3. Ocean Eyes 4. Hostage</p>'),
        ('28','1','42.42','1','2020-07-22','15.39','22.3','0.99','101.77','<p>CD Deluxe Billie Eilish - WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? (Deluxe) - Billie Eilish, lan&ccedil;ou em mar&ccedil;o de 2019 seu primeiro &aacute;lbum de est&uacute;dio CD &ndash; WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? Considerada uma das maiores apostas do pop alternativo, Billie Eilish aposta em um disco diferente de tudo que estamos costumados a ver. Com composi&ccedil;&otilde;es pr&oacute;prias, em parceria com seu irm&atilde;o, a cantora traz refer&ecirc;ncias urbanas com um pouco de eletr&ocirc;nico e rock. Dentre as faixas escolhidas, &ldquo;when the party&rsquo;s over&rdquo; j&aacute; &eacute; uma das favoritas de seus f&atilde;s. Com mais de 3 milh&otilde;es de streams nas plataformas digitais, 11 milh&otilde;es de seguidores em suas redes sociais, a &ldquo;garotinha&rdquo; de 17 anos j&aacute; &eacute; um fen&ocirc;meno nos Estados Unidos, com seis certificados de ouro e dois de platina, al&eacute;m de ter apoio de grandes artistas como: Khalid, Katy Perry, Dua Lipa, Alessia Cara e outros nomes. Dono da sua segunda maior f&atilde; base, o Brasil recebeu com muita comemora&ccedil;&atilde;o o lan&ccedil;amento de When We All Fall Asleep, Where Do We Go? E como se n&atilde;o bastasse agora o f&atilde; recebe esta vers&atilde;o Deluxe com mais 3 faixas especiais.</p><p>Repert&oacute;rio do CD: 1. !!!!!!! 2. Bad Guy 3. Xanny 4. You Should See Me In A Crown 5. All The Good Girls Go To Hell 6. Wish You Were Gay 7. When The Party&rsquo;s Over 8. 8 9. My Strange Addiction 10. Bury A Friend 11. Ilomilo 12. Listen Before You Go 13. I Love You - 14. Goodbye 15. WHEN I WAS OLDER - Music Inspired By The Movie ROMA 16. bitches broken hearts 17. everything i wanted</p>'),
        ('28','2','75.00','1','2020-07-22','11.00','7.0','7.0','7.0','<p>Cassete Lime Green Importado Billie Eilish - WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?. Cassete verde lim&atilde;o. &Eacute; o &aacute;lbum de estreia da cantora norte-americana Billie Eilish, lan&ccedil;ado em 29 de mar&ccedil;o de 2019 atrav&eacute;s das gravadoras Darkroom e Interscope Records. A1 !!!!!!!- A2 Bad Guy - A3 Xanny - A4 You Should See Me In A Crown - A5 All The Good Girls Go To Hell- A6 Wish You Were Gay - A7 When The Party&rsquo;s Over - B1 - 8 B2My Strange Addiction - B3 Bury A Friend- B4 Ilomilo - B5 Listen Before I Go - B6 I Love You - B7 Goodbye</p>'),
        ('28','5','251.91','1','2020-07-22','1.0','31.30','31.30','420.0','<p>Vinil Importado Billie Eilish - WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?. &Eacute; o &aacute;lbum de estreia da cantora norte-americana Billie Eilish, lan&ccedil;ado em 29 de mar&ccedil;o de 2019 atrav&eacute;s das gravadoras Darkroom e Interscope Records. Repert&oacute;rio: LP: A1. !!!!!!! A2. Bad Guy - A3. Xanny A4. You Should See Me In A Crown - A5. All The Good Girls Go To Hell - A6. Wish You Were Gay A7. When The Party&rsquo;s Over B1. 8 B2. My Strange Addiction - B3. Bury A Friend - B4. Ilomilo - B5. Listen Before You Go - B6. I Love You - B7. Goodbye</p>'),
        ('29','1','42.42','1','2020-12-02','15.39','22.3','0.99','101.77','<p>Billie Eilish - &#39;Happier Than Ever&#39; - CD Vers&atilde;o Standard<br /><br />Faixas<br /><br />01. Getting Older<br />02. I Didn&#39;t Change My Number<br />03. Billie Bossa Nova<br />04. my future<br />05. Oxytocin<br />06. GOLDWING<br />07. Lost Cause<br />08. Halley&#39;s Comet<br />09. Not My Responsibility<br />10. OverHeated<br />11. Everybody Dies<br />12. Your Power<br />13. NDA<br />14. Therefore I Am<br />15. Happier Than Ever<br />16. Male Fantasy</p>'),
        ('29','2','75.00','1','2020-12-02','11.00','7.0','7.0','7.0','<p>Cassete Billie Eilish - Happier Than Ever (Standard Cassette) - Importado</p><p>Repet&oacute;rio do Cassete:</p><p>01. Getting Older</p><p>02. I Didn&#39;t Change My Number</p><p>03. Billie Bossa Nova</p><p>04. my future</p><p>05. Oxytocin</p><p>06. GOLDWING</p><p>07. Lost Cause</p><p>08. Halley&#39;s Comet</p><p>09. Not My Responsibility</p><p>10. OverHeated</p><p>11. Everybody Dies</p><p>12. Your Power</p><p>13. NDA</p><p>14. Therefore I Am</p><p>15. Happier Than Ever</p><p>16. Male Fantasy</p>'),
        ('29','5','251.91','1','2020-12-02','1.0','31.30','31.30','420.0','<p>Vinil Duplo Billie Eilish - Happier Than Ever Happier Than Ever (D2C Vinyl / 1 - Golden Yellow / 2LP) Repert&oacute;rio dos LPs: 1. Getting Older 2. I Didn&#39;t Change My Number 3. Billie Bossa Nova 4. my future 5. Oxytocin 6. GOLDWING 7. Lost Cause 8. Halley&#39;s Comet 9. Not My Responsibility 10. OverHeated 11. Everybody Dies 12. Your Power 13. NDA 14. Therefore I Am 15. Happier Than Ever 16. Male Fantasy</p>');

/* KATY PERRY*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('30','1','27.00','1','2022-01-21','15.39','22.3','0.99','101.77','<p>CD Katy Perry - One Of The Boys.</p><p>Lan&ccedil;ado em junho de 2008, One of the Boys &eacute; o primeiro &aacute;lbum de est&uacute;dio de m&uacute;sica pop e oficialmente o segundo da carreira da cantora e compositora estadunidense Katy Perry, sendo seu primeiro disco oficial ap&oacute;s ter mudado de gravadora e adotado um sobrenome pseud&ocirc;nimo, acompanhados de uma significativa mudan&ccedil;a do rock crist&atilde;o de seu &aacute;lbum de estr&eacute;ia auto-intitulado. O disco foi lan&ccedil;ado nos Estados Unidos e no Canad&aacute; em 17 de junho de 2008, contendo os singles &quot;I Kissed a Girl&quot;, &quot;Hot n Cold&quot;, &quot;Thinking of You&quot; e &quot;Waking Up in Vegas&quot;, tendo o primeiro single alcan&ccedil;ado o topo da parada musical Billboard Hot 100 por sete semanas. O &aacute;lbum foi certificado Platina pela RIAA, e vendeu cerca de 4 milh&otilde;es de exemplares nos Estados Unidos.Mundialmente, o &aacute;lbum vendeu cerca de 10 milh&otilde;es de c&oacute;pias. Tamb&eacute;m recebeu uma indica&ccedil;&atilde;o ao Grammy Awards. Este &eacute; um &aacute;lbum com can&ccedil;&otilde;es inspiradas em hist&oacute;rias com ex-namorados, viagens com os amigos entre coisas que se passaram na vida da cantora.</p><p>Repert&oacute;rio do CD:</p><p>1. One of the Boys</p><p>2. I Kissed a Girl</p><p>3. Waking Up in Vegas</p><p>4. Thinking of You</p><p>5. Mannequin</p><p>6. Ur So Gay</p><p>7. Hot n Cold</p><p>8. If You Can Afford Me</p><p>9. Lost</p><p>10. Self Inflicted</p><p>11. I&#39;m Still Breathing</p><p>12. Fingerprints</p>'),
        ('31','1','27.00','1','2022-05-03','15.39','22.3','0.99','101.77','<p>CD Katy Perry - Teenage Dream: The Complete Confection.</p><p>Teenage Dream: The Complete Confection &eacute; a reedi&ccedil;&atilde;o do terceiro &aacute;lbum de est&uacute;dio da cantora norte-americana Katy Perry, intitulado Teenage Dream. Foi lan&ccedil;ado a 23 de Mar&ccedil;o de 2012 pela Capitol Records. Editado quase dois anos ap&oacute;s o original, cont&eacute;m uma vers&atilde;o ac&uacute;stica de The One That Got Away, tr&ecirc;s m&uacute;sicas in&eacute;ditas, duas parcerias com o Kanye West e a Missy Elliot e seis remisturas adicionais.</p><p>Os seus dois singles &quot;Part of Me&quot; e &quot;Wide Awake&quot; alcan&ccedil;aram a primeira e segunda posi&ccedil;&atilde;o da Billboard Hot 100. Ambos venderam mais de dois milh&otilde;es de descargas digitais cada um no pa&iacute;s; juntando as seis faixas de trabalho lan&ccedil;adas anteriormente, Teenage Dream obteve um recorde na era digital por mais singles multi-platinados num disco, superando o feito anterior conseguido por The Dutchess de Fergie com cinco multi-platinas.</p><p>Repert&oacute;rio do CD: 1. Teenage Dream 2. Last Friday Night (T.G.I.F.) 3. California Gurls (com Snoop Dogg) 4. Firework 5. Peacock 6. Circle the Drain 7. The One That Got Away 8. E.T. 9. Who Am I Living For? 10. Pearl 11. Hummingbird Heartbeat 12. Not Like the Movies 13. The One That Got Away (ac&uacute;stico) 14. Part of Me 15. Wide Awake 16. Dressin&#39; Up 17. E.T. (com Kanye West) 18. Last Friday Night (T.G.I.F.) (com Missy Elliott) 19. Tommie Sunshine&#39;s Megasix Smash-Up</p>'),
        ('31','5','251.91','1','2022-05-03','1.0','31.30','31.30','420.0','<p>Vinil Duplo Katy Perry - Teenage Dream - Explicit - Importado</p><p>Lan&ccedil;ado em 24 de agosto de 2010, Teenage Dream &eacute; o terceiro &aacute;lbum de est&uacute;dio da cantora e compositora estadunidense Katy Perry.</p><p>Repert&oacute;rio dos LPs:</p><p>Disco 1 Lado A; 1. Teenage Dream 2. Last Friday Night (T.G.I.F.) 3. California Gurls (com Snoop Dogg)</p><p>Disco 1 Lado B; 4. Firework 5. Peacock 6. Circle the Drain</p><p>Disco 2 Lado C; 7. The One That Got Away 8. E.T. 9. Who Am I Living For?</p><p>Disco 2 Lado D; 10. Pearl 11. Hummingbird Heartbeat 12. Not Like the Movies</p>'),
        ('32','1','27.00','1','2022-05-03','15.39','22.3','0.99','101.77','<p>CD Katy Perry - Witness (Jewel Case)</p><p>Witness reflete todas as mudan&ccedil;as no mundo e na vida pessoal de Katy. O projeto, que conta com 15 faixas, traduz toda a maturidade da artista que j&aacute; chega ao seu 5&ordm; &aacute;lbum de est&uacute;dio. Com &ldquo;Chained to the Rhythm&rdquo;, &ldquo;Bon App&eacute;tit&rdquo;, &ldquo;Swish Swish&rdquo; e outros sucessos, o CD promete fazer a alegria dos f&atilde;s. Mais uma vez a ganhadora de dois emmys se reafirma com uma das maiores divas Pop da atualidade.</p><p>Repert&oacute;rio do CD: 1. Witness 2. Hey Hey Hey 3. Roulette 4. Swish Swish 5. D&eacute;j&agrave; Vu 6. Power 7. Mind Maze 8. Miss You More 9. La Vie 10. Tsunami 11. Bon App&eacute;tit 12. Bigger Than Me 13. Save As Draft 14. Pendulum 15. Into Me You See</p>'),
        ('32','5','251.91','1','2022-05-03','1.0','31.30','31.30','420.0','<p>Vinil Duplo Katy Perry - Witness (Importado).</p><p>Lan&ccedil;ado em 9 de junho de 2017, Witness reflete todas as mudan&ccedil;as no mundo e na vida pessoal de Katy. O projeto, que conta com 15 faixas, traduz toda a maturidade da artista que j&aacute; chega ao seu 5&ordm; &aacute;lbum de est&uacute;dio. Com &ldquo;Chained to the Rhythm&rdquo;, &ldquo;Bon App&eacute;tit&rdquo;, &ldquo;Swish Swish&rdquo; e outros sucessos, o CD promete fazer a alegria dos f&atilde;s. Mais uma vez a ganhadora de dois emmys se reafirma com uma das maiores divas Pop da atualidade.</p><p>Repert&oacute;rio dos LPs:</p><p>Disco 1 Lado A; 1. Witness 2. Hey Hey Hey 3. Roulette 4. Swish Swish</p><p>Disco 1 Lado B; 5. D&eacute;j&agrave; Vu 6. Power 7. Mind Maze 8. Miss You More</p><p>Disco 2 Lado C; 9. Chained to the Rhythm (feat. Skip Marley) 10. Tsunami 11. Bon App&eacute;tit 12. Bigger Than Me</p><p>Disco 2 Lado D; 13. Save As Draft 14. Pendulum 15. Into Me You See</p>'),
        ('33','1','27.00','1','2021-01-19','15.39','22.3','0.99','101.77','<p>CD Katy Perry - SMILE.</p><p>Lan&ccedil;ado em 28 de agosto de 2020, tr&ecirc;s anos depois do seu antecessor Witness de 2017, Smile &eacute; o sexto &aacute;lbum de est&uacute;dio da cantora e compositora norte-americana Katy Perry. Ela descreveu o &aacute;lbum como sua &quot;jornada em dire&ccedil;&atilde;o &agrave; luz, com hist&oacute;rias de resili&ecirc;ncia, esperan&ccedil;a e amor&quot;. Musicalmente um &aacute;lbum pop, Smile promove temas como autoajuda e empoderamento. O &aacute;lbum atingiu um desempenho no top 5 da Austr&aacute;lia, Canad&aacute;, Nova Zel&acirc;ndia, Esc&oacute;cia, Espanha, o Reino Unido, e os Estados Unidos, o top 10 na Irlanda e It&aacute;lia.</p><p>Repert&oacute;rio do CD: 1.Never Really Over 2.Cry About It Later 3.Teary Eyes 4.Daisies 5.Resilient 6.Not the End of the World 7.Smile - MAIN VERSION 8.Champagne Problems 9.Tucked 10.Harleys In Hawaii 11.Only Love 12.What Makes A Woman</p>'),
        ('33','2','110.87','1','2021-01-19','11.00','7.0','7.0','7.0','<p>Cassete Katy Perry - Smile - Importado.</p><p>Lan&ccedil;ado em 28 de agosto de 2020, tr&ecirc;s anos depois do seu antecessor Witness de 2017, Smile &eacute; o sexto &aacute;lbum de est&uacute;dio da cantora e compositora norte-americana Katy Perry. Ela descreveu o &aacute;lbum como sua &quot;jornada em dire&ccedil;&atilde;o &agrave; luz, com hist&oacute;rias de resili&ecirc;ncia, esperan&ccedil;a e amor&quot;. Musicalmente um &aacute;lbum pop, Smile promove temas como autoajuda e empoderamento. O &aacute;lbum atingiu um desempenho no top 5 da Austr&aacute;lia, Canad&aacute;, Nova Zel&acirc;ndia, Esc&oacute;cia, Espanha, o Reino Unido, e os Estados Unidos, o top 10 na Irlanda e It&aacute;lia.</p><p>Repert&oacute;rio do Cassete: 1. Never Really Over 2. Cry About It Later 3. Teary Eyes 4. Daisies 5. Resilient 6. Not The End of the World 7. Smile 8. Champagne Problems 9. Tucked 10. Harleys in Hawaii 11. Only Love 12. What Makes A Woman</p><p>**todas as perspectivas contidas neste material s&atilde;o meramente ilustrativas, podendo sofrer altera&ccedil;&otilde;es, inclusive quanto &agrave; cor, forma, textura e tamanho.</p>'),
        ('33','5','251.91','1','2021-01-19','1.0','31.30','31.30','420.0','<p>Lan&ccedil;ado em 28 de agosto de 2020, tr&ecirc;s anos depois do seu antecessor Witness de 2017, Smile &eacute; o sexto &aacute;lbum de est&uacute;dio da cantora e compositora norte-americana Katy Perry. Ela descreveu o &aacute;lbum como sua &quot;jornada em dire&ccedil;&atilde;o &agrave; luz, com hist&oacute;rias de resili&ecirc;ncia, esperan&ccedil;a e amor&quot;. Musicalmente um &aacute;lbum pop, Smile promove temas como autoajuda e empoderamento. O &aacute;lbum atingiu um desempenho no top 5 da Austr&aacute;lia, Canad&aacute;, Nova Zel&acirc;ndia, Esc&oacute;cia, Espanha, o Reino Unido, e os Estados Unidos, o top 10 na Irlanda e It&aacute;lia.</p><p>Repert&oacute;rio do CD: 1.Never Really Over 2.Cry About It Later 3.Teary Eyes 4.Daisies 5.Resilient 6.Not the End of the World 7.Smile - MAIN VERSION 8.Champagne Problems 9.Tucked 10.Harleys In Hawaii 11.Only Love 12.What Makes A Woman</p>'),
        ('34','5','251.91','1','2021-01-19','1.0','31.30','31.30','420.0','<p>VINIL Katy Perry - Smile D2C Exclusive Picture Disc</p><p>Lan&ccedil;ado em 28 de agosto de 2020, tr&ecirc;s anos depois do seu antecessor Witness de 2017, Smile &eacute; o sexto &aacute;lbum de est&uacute;dio da cantora e compositora norte-americana Katy Perry. Ela descreveu o &aacute;lbum como sua &quot;jornada em dire&ccedil;&atilde;o &agrave; luz, com hist&oacute;rias de resili&ecirc;ncia, esperan&ccedil;a e amor&quot;. Musicalmente um &aacute;lbum pop, Smile promove temas como autoajuda e empoderamento. O &aacute;lbum atingiu um desempenho no top 5 da Austr&aacute;lia, Canad&aacute;, Nova Zel&acirc;ndia, Esc&oacute;cia, Espanha, o Reino Unido, e os Estados Unidos, o top 10 na Irlanda e It&aacute;lia.</p><p>Repert&oacute;rio do LP:</p><p>Lado A: A1. Never Really Over A2. Cry About It Later A3. Teary Eyes A4. Daisies A5. Resilient A6. Not The End Of The World</p><p>Lado B: B1. Smile (Feat. Diddy) B2. Champagne Problems B3. Tucked B4. Harleys In Hawaii B5. Only Love B6. What Makes A Woman</p><p>**todas as perspectivas contidas neste material s&atilde;o meramente ilustrativas, podendo sofrer altera&ccedil;&otilde;es, inclusive quanto &agrave; cor, forma, textura e tamanho.</p>');

insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('35','1','53.25','1','2022-11-11','15.39','22.3','0.99','101.77','<p>Tracklist:<br />1. End of My Life<br />2. Arizona Pretty<br />3. Good Day to be My Dealer<br />4. Trainwreck<br />5. Falling From The Sky<br />6. Alright OK<br />7. Cheerleader<br />8. Queen Bitch<br />9. Another Day in Paradise<br />10. Down With The Ship<br />11. Loser<br />12. Sellout</p>'),
        ('35','5','133.13','1','2022-11-11','1.0','31.30','31.30','420.0','<p>Tracklist:<br />1. End of My Life<br />2. Arizona Pretty<br />3. Good Day to be My Dealer<br />4. Trainwreck<br />5. Falling From The Sky<br />6. Alright OK<br />7. Cheerleader<br />8. Queen Bitch<br />9. Another Day in Paradise<br />10. Down With The Ship<br />11. Loser<br />12. Sellout</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('47','1','48.90','1','2022-08-30','2.0','12.0','15.0','110.0','<p>CD Lady Gaga - The Fame.</p><p>The Fame foi lan&ccedil;ado em 19 de agosto de 2008 no Canad&aacute;. The Fame &eacute; o &aacute;lbum de estreia de est&uacute;dio gravado pela artista musical americana Lady Gaga. Depois de escrever v&aacute;rias can&ccedil;&otilde;es para outros artistas, Gaga decidiu lan&ccedil;ar este &aacute;lbum. O tema principal das faixas &eacute; sobre como algu&eacute;m pode sentir-se famoso sendo uma celebridade.</p><p>As m&uacute;sicas s&atilde;o em sua maioria inspiradas pelo amor de Gaga pela fama, e lida com as complexidades de um estilo de vida rico e famoso, visualizado pela mesma. Musicalmente, &eacute; inspirado em electropop e synthpop dos anos 80, incorporando m&uacute;sica de dan&ccedil;a e refr&otilde;es suaves.</p><p>Repert&oacute;rio do CD: 1.Just Dance (com Colby O Donis) 2.LoveGame 3.Paparazzi 4.Poker Face 5.Eh, Eh (Nothing Else I Can Say) 6.Beautiful, Dirty, Rich 7.The Fame 8.Money Honey 9.Starstruck (com Space Cowboy e Flo Rida) 10.Boys Boys Boys 11.Paper Gangsta 12.Brown Eyes 13.I Like It Rough 14.Summerboy Disco Heven (Bonus Track)</p>'),
        ('47','5','349.90','1','2022-08-30','1.0','31.30','31.30','376.0','<p>VINIL Duplo Lady Gaga - The Fame (Colored vinyl version) - Importado. Lan&ccedil;ado em 19 de agosto de 2008, The Fame &eacute; o &aacute;lbum de estreia de est&uacute;dio gravado pela artista musical estadunidense Lady Gaga. The Fame ganhou v&aacute;rios pr&ecirc;mios desde o seu lan&ccedil;amento. Nos Estados Unidos, o &aacute;lbum foi indicado a um total de cinco Pr&ecirc;mios Grammy na 52&ordm; edi&ccedil;&atilde;o, incluindo o &Aacute;lbum do Ano. Na edi&ccedil;&atilde;o de 2010 venceu na categoria Melhor &Aacute;lbum de Eletr&ocirc;nica/Dance e Melhor Grava&ccedil;&atilde;o Dance por &quot;Poker Face&quot;. No dia 16 de fevereiro de 2010, ganhou na cerim&oacute;nia BRIT Awards de 2010 na categoria Melhor &Aacute;lbum Internacional.</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('48','1','39.70','1','2019-12-07','2.0','12.0','15.0','110.0','<p>CD Lady Gaga - The Remix.</p><p>Lan&ccedil;ado no Jap&atilde;o em 3 de mar&ccedil;o de 2010, o trabalho cont&eacute;m remixes das can&ccedil;&otilde;es de seu primeiro disco de est&uacute;dio, The Fame (2008), e seu terceiro extended play (EP), The Fame Monster (2009).</p><p>A artista do ano de 2009! E o sucesso continua... Em 2009... Vencedora de 2 Grammys, incluindo melhor grava&ccedil;&atilde;o dance com Poker Face e melhor &aacute;lbum eletr&ocirc;nico/dance com The Fame. Vencedora de 3 Brit Awards, incluindo melhor &aacute;lbum internacional com The Fame, melhor cantora e artista revela&ccedil;&atilde;o. Em 2010... Recorde de visualiza&ccedil;&otilde;es na rede: mais de 1 bilh&atilde;o de views. Bad Romance &eacute; o v&iacute;deo mais visto da hist&oacute;ria do Youtube com 250 milh&otilde;es de views. The Remix inclui 17 remixes - assinados pelos maiores DJs - dos sucessos de The Fame e The Fame Monster. Inclui 2 remixes exclusivos - Alejandro (Sound Of Arrows remix) e Dance In The Dark (Monarchy remix.) The Remix, lan&ccedil;ado primeiro no Jap&atilde;o, estreou em primeiro lugar nos charts de vendas.</p><p>Repert&oacute;rio do CD:</p><p>1. Just Dance (Richard Vission Remix)</p><p>2. Poker Face (LLG vs. GLG Radio Mix Remix)</p><p>3. LoveGame (Chew Fu Ghettohouse Fix) (com Marilyn Manson)</p><p>4. Eh, Eh (Nothing Else I Can Say) (Frankmusik Remix)</p><p>5. Paparazzi (Stuart Price Remix)</p><p>6. Boys Boys Boys (Manhattan Clique Remix)</p><p>7. The Fame (Glam as You Remix)</p><p>8. Bad Romance (Starsmith Remix)</p><p>9. Telephone (Passion Pit Remix) (com Beyonc&eacute;)</p><p>10. Alejandro (The Sound of Arrows Remix)</p><p>11. Dance in the Dark (Monarchy &#39;Stylites&#39; Remix)</p><p>12. Just Dance (Deewaan Remix) (com Ashking, Wedis, Lush, e Young Thoro)</p><p>13. LoveGame (Robots to Mars Remix)</p><p>14. Eh, Eh (Nothing Else I Can Say) (Pet Shop Boys Remix)</p><p>15. Poker Face&quot; (Live at The Cherrytree House Piano &amp; Voice Version)</p><p>16. Bad Romance (Grum Remix)</p><p>17. Telephone (Alphabeat Remix) (com Beyonc&eacute;)</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('49','1','45.90','1','2018-12-05','2.0','12.0','15.0','110.0','<p>CD Lady Gaga - Born This Way.</p><p>Lan&ccedil;ado em 23 de maio de 2011, Born This Way &eacute; o segundo &aacute;lbum de est&uacute;dio da cantora, compositora e produtora musical norte-americana Lady Gaga.</p><p>Born This Way &eacute; notavelmente diferente do &aacute;lbum anterior de Gaga, como incorpora uma vasta gama de elementos de v&aacute;rios g&eacute;neros musicais, inclusive a &oacute;pera, o heavy metal, o disco e o rock and roll, e funde os elementos com sons de electropop e dance. Tamb&eacute;m &eacute; fortemente inspirado pelo synthpop e pela m&uacute;sica electr&oacute;nica das d&eacute;cadas de 80 e 90. Na grava&ccedil;&atilde;o das can&ccedil;&otilde;es, Gaga trabalhou com v&aacute;rios produtores, incluindo RedOne, Fernando Garibay, Jeppe Laursen e DJ White Shadow, e contou com a participa&ccedil;&atilde;o de artistas como Clarence Clemons e Brian May. Com Born This Way, a cantora teve mais controle de sua direc&ccedil;&atilde;o musical e composi&ccedil;&atilde;o.</p><p>Repert&oacute;rio do CD: 1. Marry the Night 2. Born This Way 3. Government Hooker 4. Judas 5. Americano 6. Hair 7. Schei&szlig;e 8. Bloody Mary 9. Bad Kids 10. Highway Unicorn (Road to Love) 11. Heavy Metal Lover 12. Electric Chapel 13. Yo&uuml; and I 14. The Edge of Glory</p>'),
        ('49','5','419.00','1','2018-12-05','1.0','31.30','31.30','376.0','<p>O &eacute;pico e inesquec&iacute;vel segundo &aacute;lbum de Lady Gaga, Born This Way, est&aacute; dispon&iacute;vel aqui em vinil em uma edi&ccedil;&atilde;o especial tripla em LP lan&ccedil;ada em comemora&ccedil;&atilde;o ao seu d&eacute;cimo anivers&aacute;rio.&nbsp;Celebrando seu esp&iacute;rito &uacute;nico, assim como voc&ecirc; &eacute;, o &aacute;lbum dance-pop traz elementos de &oacute;pera, disco e heavy metal para explorar a sexualidade, feminismo e express&atilde;o com uma veia Avant-Garde no verdadeiro estilo Gaga.&nbsp;Apresentando os singles, &quot;Born This Way&quot; e &quot;The Edge of Glory&quot;, al&eacute;m de seis novas vers&otilde;es de favoritos reinventados por artistas que representam e defendem a comunidade LGBTQIA+. (2021, Interscope.)</p><p>Tracklisting<br />DISCO&nbsp;1<br />Lado A<br />1. Marry The Night<br />2. Born This Way<br />3. Government Hooker<br />4. Judas<br />5. Americano<br />Lado B<br />1. Hair<br />2. Schei&szlig;e<br />3. Bloody Mary<br />4. Black Jesus + Amen Fashion</p><p>DISCO 2<br />Lado C<br />1. Bad Kids<br />2. Fashion Of His Love<br />3. Highway Unicorn (Road To Love)<br />4. Heavy Metal Lover<br />Lado D<br />1. Electric Chapel<br />2. The Queen<br />3. Yo&uuml; And I<br />4. The Edge Of Glory</p><p>DISCO 3<br />Lado E<br />1. Marry The Night<br />2. Judas<br />3. Highway Unicorn (Road To Love)<br />Lado F<br />1. Yo&uuml; And I<br />2. The Edge Of Glory<br />3. Born This Way [The Country Road Version]</p>'),
        ('50','1','45.90','1','2018-12-05','2.0','12.0','15.0','110.0','<p>CD Duplo Lady Gaga - Born This Way (Special Edition).</p><p>Lan&ccedil;ado em 23 de Maio de 2011, Born This Way &eacute; o segundo &aacute;lbum de est&uacute;dio da cantora, compositora, multi-instrumentista, produtora musical e atriz norte-americana Lady Gaga. Aqui temos a vers&atilde;o em edi&ccedil;&atilde;o especial e CD duplo.</p><p>Repert&oacute;rio dos CDs;</p><p>CD1; 1. Marry The Night 2. Born This Way 3. Government Hooker 4. Judas 5. Americano 6. Hair 7.Shei&szlig;e 8. Bloody Mary 9. Black Jesus &dagger; Amen Fashion 10. Bad Kids 11. Fashion Of His Love 12. Highway Unicorn (Road To Love) 13. Heavy Metal Lover 14. Electric Chapel 15. The Queen 16. Yo&Uuml; And I 17. The Edge Of Glory</p><p>Disc CD2; 1. Born This Way (Country Road Version) 2. Judas (DJ White Shadow Remix) 3. Marry The Night (Zedd Remix) 4. Shei&szlig;e (DJ White Shadow Mugler) 5. Fashion Of His Love (Fernando Garibay Remix)</p>'),
        ('50','5','599.00','1','2018-12-05','1.0','31.30','31.30','376.0','<p>Lan&ccedil;amento mais do que esperado em edi&ccedil;&atilde;o limitada do segundo &aacute;lbum da cantora&nbsp;Lady Gaga. &quot;Born this Way&quot; &eacute; uma das obras-primas do pop mundial e ganha vers&atilde;o em vinil vermelho, exclusivo da Urban Outfitters. Inclui os singles &quot;Born this Way&quot;,&nbsp;&quot;The Edge of Glory&quot;, &quot;Judas&quot;, &quot;Marry the Night&quot; e &quot;You And I&quot;.&nbsp;</p><p><u>Tracklist</u><br /><strong>DISC 1</strong><br />Side A<br />1. Marry The Night<br />2. Born This Way<br />3. Government Hooker<br />4. Judas<br />5. Americano</p><p>Side B<br />1. Hair<br />2. Schei&szlig;e<br />3. Bloody Mary<br />4. Black Jesus + Amen Fashion</p><p><strong>DISC 2</strong><br />Side C<br />1. Bad Kids<br />2. Fashion Of His Love<br />3. Highway Unicorn (Road To Love)<br />4. Heavy Metal Lover</p><p>Side D<br />1. Electric Chapel<br />2. The Queen<br />3. You&nbsp;And I<br />4. The Edge Of Glory</p>'),
        ('51','1','45.90','1','2018-12-05','2.0','12.0','15.0','110.0','<p>CD Lady Gaga - Born This Way-The Remix.</p><p>Born This Way, terceiro &aacute;lbum de est&uacute;dio da maior artista pop, vendeu mais de 5 milh&otilde;es de c&oacute;pias no mundo. Lady Gaga bateu mais um recorde, &eacute; a &uacute;nica pessoa no mundo a ter 15 milh&otilde;es de seguidores no Twitter. &quot;Born This Way&quot; bateu um recorde na ind&uacute;stria da m&uacute;sica ao se tornar, em toda a hist&oacute;ria, o single que alcan&ccedil;ou mais rapidamente 1 milh&atilde;o de c&oacute;pias vendidas em todo o mundo.</p><p>Born This Way: The Remix &eacute; o segundo &aacute;lbum de remixes da artista musical norte-americana Lady Gaga.</p><p>O disco foi lan&ccedil;ado em 18 de Novembro de 2011 em formato f&iacute;sico e digital. The Remix inclui 14 remixes - assinados pelos maiores DJs - dos sucessos de Born This Way. O maior fen&ocirc;meno da m&uacute;sica pop! Mais de 15 milh&otilde;es de &aacute;lbuns e 51 milh&otilde;es de siongles vendidos no mundo.</p><p>Repert&oacute;rio do CD: 1.Born This Way (Zedd Remix) 2.Judas (Goldfrapp Remix) 3.The Edge of Glory (Foster the People Remix) 4.Yo&uuml; and I (Wild Beasts Remix) 5.Marry the Night (The Weeknd &amp; Ilangelo Remix) 6.Black Jesus Amen Fashion (Michael Woods Remix) 7.Bloody Mary (The Horrors Remix) 8.Schei&szlig;e (Gu&eacute;na LG Remix) 9.Americano (Gregori Klosman Remix) 10.Electric Chapel (Two Door Cinema Club Remix) 11.Yo&uuml; and I (Metronomy Remix) 12.Judas (Hurts Remix) 13.Born This Way (Twin Shadow Remix) 14.The Edge of Glory (Sultan &amp; Ned Shepard Remix)</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('52','1','45.90','0','2019-07-17','2.0','12.0','15.0','110.0','GAGA'),
        ('53','4','195.24','1','2019-07-17','2.0','13.50','19.0','107.00','<p>DVD Lady Gaga - Presents The Monster Ball Tour At Madison Square Garden.</p><p>Lan&ccedil;ado em novembro de 2011 Lady Gaga Presents The Monster Ball Tour At Madison Square Garden &eacute; o primeiro DVD do maior fen&ocirc;meno da m&uacute;sica pop! Lady Gaga lan&ccedil;a &quot;Monster Ball at Madison Square Garden&quot; gravado em Nova York, especial ddo canal HBO e vencedor do Emmy Award, com imagens in&eacute;ditas e exclusivas. O especial mostra, al&eacute;m do concerto, os bastidores da turn&ecirc; e mostra at&eacute; uma cena em que Gaga est&aacute; falando com seu maquiador sobre o passado. &quot;Born This Way&quot;, terceiro &aacute;lbum de est&uacute;dio de Lady Gaga, bateu o recorde do iTunes pela subida mais r&aacute;pida ao 1&ordm; lugar no dia do lan&ccedil;amento. Os singles do &aacute;lbum incluindo &quot;Born This Way&quot;, &quot;Judas&quot;, &quot;The Edge Of Glory&quot; e &quot;You and I&quot; j&aacute; venderam juntos mais de 7 milh&otilde;es de c&oacute;pias somente nos Estados Unidos. Em menos de tr&ecirc;s anos, Lady Gaga ganhou cinco Grammy Awards, entre doze indica&ccedil;&otilde;es, dois recordes do Guiness World Records, e tem uma venda estimada de 23 milh&otilde;es de &aacute;lbuns e 64 milh&otilde;es de singles em todo o mundo. Os maiores sucessos de Lady Gaga num registro em DVD imperd&iacute;vel!</p><p>Repert&oacute;rio do DVD:</p><p>Bloco I: New York City 1. Dance In The Dark 2. Glitter and Grease 3. Just Dance 4. Beautiful, Dirty, Rich 5. The Fame</p><p>Bloco II: New York City Subway 6. LoveGame 7. Boys Boys Boys 8. Money Honey 9. Telephone 10. Speechless 11. Yo&uuml; and I 12. So Happy I Could Die 13. Monster</p><p>Bloco III: Central Park 14. Teeth 15. Alejandro 16. Poker Face Act IV: The Monster Ball 17. Paparazzi 18. Bad Romance 19. Born This Way</p><p>Bonus: Born This Way A Capella / Backstage / Phto Gallery</p><p>Informa&ccedil;&otilde;es Adicionais: Formato de tela: 16:9 Widescreen / Sistema de &Aacute;udio: Dolby Digital Stereo e 5.1 Surround / Legendas: Ingl&ecirc;s, Franc&ecirc;s, Alem&atilde;o, Espanhol, Portugu&ecirc;s e Italiano.</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('54','1','45.90','1','2018-12-05','2.0','12.0','15.0','110.0','<p>CD Lady Gaga - Artpop DELUXE.</p><p>Lan&ccedil;ado em 06 de novembro de 2013, ARTPOP &eacute; o aguardado &aacute;lbum do fen&ocirc;meno pop Lady Gaga!</p><p>ARTPOP traz o sucesso Applause, que &eacute; o primeiro single do &aacute;lbum e j&aacute; tem mais 1 milh&atilde;o de c&oacute;pias vendidas. Applause estreou em n&uacute;mero 1 nas paradas de mais de 35 pa&iacute;ses.</p><p>ARTPOP &eacute; um dos maiores lan&ccedil;amentos do ano!!!</p><p>Lady Gaga &eacute; uma das maiores artistas da atualidade e a grande revela&ccedil;&atilde;o da m&uacute;sica pop nos &uacute;ltimos anos. Ao todo s&atilde;o mais de 24 milh&otilde;es de &aacute;lbuns e 90 milh&otilde;es de singles vendidos ao redor do mundo. S&oacute; o &aacute;lbum &lsquo;The Fame&rsquo;, disco de estreia da cantora, vendeu mais de 15 milh&otilde;es de c&oacute;pias.</p><p>Lady Gaga tamb&eacute;m acumula pr&ecirc;mios importantes em sua carreira, como 5 pr&ecirc;mios Grammy e 13 pr&ecirc;mios MTV Music Awards.</p><p>Lady Gaga &eacute; uma das maiores personalidades vivas nas m&iacute;dias sociais com mais de 58 milh&otilde;es de f&atilde;s no Facebook, mais de 39 milh&otilde;es de seguidores no Twitter e 2.2 visualiza&ccedil;&otilde;es combinadas em seus v&iacute;deos.</p><p>Lady Gaga &eacute; a &uacute;nica artista a atingir a marca de 5 milh&otilde;es de singles vendidos com seus primeiros dois hits.</p><p>Repert&oacute;rio do CD: 01. Aura 02. Venus 03. G.U.Y. 04. Sexxx dreams 05. Jewels n&rsquo; drugs 06. MANiCURE 07. Do what you want 08. ARTPOP 09. Swine 10. Donatella 11. Fashion! 12. Mary Jane Holland 13. Dope 14. Gypsy 15. Applause</p>'),
        ('54','5','419.00','1','2018-12-05','1.0','31.30','31.30','376.0','<p>VINIL Duplo Lady Gaga - ARTPOP (NEW Explicit Vinyl/2LP) - Importado</p>');

/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('55','1','44.90','1','2018-12-05','2.0','13.0','7.50','150.0','<p>CD Lady Gaga - Joanne (CD Deluxe)</p><p>Lan&ccedil;ado em 21 de outubro de 2016, Joanne &eacute; o quinto &aacute;lbum de est&uacute;dio da artista musical estadunidense Lady Gaga. Gaga nomeou o &aacute;lbum de Joanne em homenagem &agrave; sua tia paterna, Joanne Stefani Germanotta, que faleceu em 18 de dezembro de 1974 aos 19 anos de idade.</p><p>Repert&oacute;rio do CD: 1. Diamond Heart 2. A-Yo 3. Joanne 4. John Wayne 5. Dancin&#39; In Circles 6. Perfect Illusion 7. Million Reasons 8. Sinner&#39;s Prayer 9. Come To Mama 10. Hey Girl (Feat. Florence Welch) 11. Angel Down 12. Grigio Girls 13. Just Another Day 14. Angel Down (Work Tape)</p>'),
        ('55','5','419.00','1','2018-12-05','1.0','31.30','31.30','376.0','<p>VINIL Duplo Lady Gaga - Joanne (Standard) - Importado.</p><p>Lan&ccedil;ado em 21 de outubro de 2016, Joanne &eacute; o quinto &aacute;lbum de est&uacute;dio da artista musical estadunidense Lady Gaga. Gaga nomeou o &aacute;lbum de Joanne em homenagem &agrave; sua tia paterna, Joanne Stefani Germanotta, que faleceu em 18 de dezembro de 1974 aos 19 anos de idade.</p><p>Repert&oacute;rio dos LPs: Disco 1 Lado A: 1. Diamond Heart 2. A-Yo 3. Joanne Disco 1 Lado B: 4. John Wayne 5. Dancin&#39; In Circles 6. Perfect Illusion 7. Million Reasons Disco 2 Lado A: 8. Sinner&#39;s Prayer 9. Come To Mama 10. Hey Girl (Feat. Florence Welch) Disco 2 Lado B: 11. Angel Down 12. Grigio Girls 13. Just Another Day 14. Angel Down (Work Tape)</p>');
        
/*LADY GAGA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
        values
        ('56','1','179.90','1','2022-09-13','2.0','12.0','7.50','110.0','<p>Repert&oacute;rio do CD: 1. &quot;Chromatica I&quot; 2. &quot;Alice&quot; 3. Stupid Love&quot; 4. &quot;Rain On Me&quot; (with Ariana Grande) 5. &quot;Free Woman&quot; 6. &quot;Fun Tonight&quot; 7. &quot;Chromatica II&quot; 8. &quot;911&quot; 9. &quot;Plastic Doll&quot; 10. &quot;Sour Candy&quot; (with Blackpink) 11. &quot;Enigma&quot; 12. &quot;Replay&quot; 13. &quot;Chromatica III&quot; 14. &quot;Sine From Above&quot; (with Elton John) 15. &quot;1000 Doves&quot; 16. &quot;Babylon&quot;</p>'),
        ('56','2','110.87','0','2021-01-19','11.00','7.0','7.0','7.0','GAGA'),
        ('56','5','419.00','1','2022-09-13','31.39','31.39','1.19','235.87','<p>Chromatica &eacute; o sexto &aacute;lbum de est&uacute;dio de Lady Gaga. Agora dispon&iacute;vel em vinil preto de 180 gramas em uma capa especial com tr&ecirc;s dobras.</p>'),
        ('57','1','44.90','1','2022-09-13','2.0','12.0','7.50','110.0','<p>CD LADY GAGA - DAWN OF CHROMATICA</p><p>Faixas: 1. Alice (LSDXOXO Remix) 2. Stupid Love (COUCOU CHLOE Remix) 3. Rain on Me (With Ariana Grande) (Arca Remix) 4. Free Woman (Rina Sawayama &amp; Clarence Clarity Remix) 5. Fun Tonight (Pabllo Vittar Remix) 6. 911 (Charli XCX &amp; A. G. Cook Remix) 7. Plastic Doll (Ashnikko Remix) 8. Sour Candy (With BLACKPINK) (Shygirl &amp; Mura Masa Remix) 9. Enigma (Doss Remix) 10. Replay (Dorian Electra Remix) 11. Sine From Above (with Elton John) (Chester Lockhart, Mood Killer &amp; Lil Texas Remix) 12. 1000 Doves (Planningtorock Remix) 13. Babylon (Bree Runway &amp; Jimmy Edgar Remix) 14. Babylon (Haus Labs Version)</p>'),
        ('57','5','389.90','1','2022-09-13','0.70','31.30','31.30','370.0','<p>VINIL LADY GAGA - DAWN OF CHROMATICA – IMPORTADO</p><p>Faixas: 1. Alice (LSDXOXO Remix) 2. Stupid Love (COUCOU CHLOE Remix) 3. Rain on Me (With Ariana Grande) (Arca Remix) 4. Free Woman (Rina Sawayama &amp; Clarence Clarity Remix) 5. Fun Tonight (Pabllo Vittar Remix) 6. 911 (Charli XCX &amp; A. G. Cook Remix) 7. Plastic Doll (Ashnikko Remix) 8. Sour Candy (With BLACKPINK) (Shygirl &amp; Mura Masa Remix) 9. Enigma (Doss Remix) 10. Replay (Dorian Electra Remix) 11. Sine From Above (with Elton John) (Chester Lockhart, Mood Killer &amp; Lil Texas Remix) 12. 1000 Doves (Planningtorock Remix) 13. Babylon (Bree Runway &amp; Jimmy Edgar Remix) 14. Babylon (Haus Labs Version)</p>');

/*MADONNA*/
insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('58','1','67.92','1','2019-10-16','2.0','13.0','7.50','120.0','<p>CD Madonna - MDNA (Standard Explicit Version) - Importado</p><p>Repert&oacute;rio do CD: 1. Girl Gone Wild 2. Gang Bang 3. I&#39;m Addicted 4. Turn Up The Radio 5. Give Me All Your Luvin&#39; 6. Some Girls 7. Superstar 8. I Don&#39;t Give A 9. I&#39;m A Sinner 10. Love Spent 11. Masterpiece 12. Falling Free</p>');

insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('59','4','196.00','1','2017-09-29','19.2','13.7','1.5','111.0','<p>Para comemorar o aniversário da material girl, madonna anunciou seu novo projeto ao vivo em dvd com conteúdo extra madonna: hebel heart tour.</p>');

insert into tb_cassandra_product(fk_version, fk_format, vl_price, st_product, dt_added, vl_height, vl_width, vl_length, vl_weight, description_product)
	values
        ('60','1','179.90','1','2020-12-17','2.0','12.0','7.50','110.0','<p>CD Madonna - Madame X (Standard CD) - Importado</p><p>Repert&oacute;rio do CD: 1. Madonna + Maluma &ndash; Medell&iacute;n 2. Madonna &ndash; Dark Ballet 3. Madonna &ndash; God Control 4. Madonna + Quavo &ndash; Future 5. Madonna &ndash; Batuka 6. Madonna &ndash; Killers Who Are Partying 7. Madonna + Swae Lee &ndash; Crave 8. Madonna &ndash; Crazy 9. Madonna &ndash; Come Alive 10. Madonna &ndash; Faz Gostoso - Featuring &ndash; Anitta 11. Madonna &ndash; Bitch I&#39;m Loca - Featuring &ndash; Maluma 12. Madonna &ndash; I Don&#39;t Search I Find 13. Madonna &ndash; I Rise</p>'),
        ('60','5','419.00','1','2020-12-17','31.39','31.39','1.19','235.87','<p>Vinil Duplo Madonna - Madame X (2LP - Main) - Importado.</p><p>A rainha do pop, Madonna, lan&ccedil;ou seu &aacute;lbum,&quot;MADAME X&quot;. O d&eacute;cimo quarto disco de est&uacute;dio da cantora, que cont&eacute;m faixas em ingl&ecirc;s, espanhol e portugu&ecirc;s, conta com participa&ccedil;&otilde;es como as de Maluma, Swae Lee, Quavo e Anitta.</p><p>Por meio de uma rede social, Madonna revelou a identidade da misteriosa Madame X: &quot;Decidi chamar meu &aacute;lbum de MADAME X. Uma agente secreta viajando ao redor do mundo, trocando sua identidade, lutando por liberdade, trazendo luz a lugares sombrios.</p><p>Ela &eacute; uma professora de dan&ccedil;a, uma professora, uma chefe de estado, uma governanta, uma prisioneira, uma estudante, uma professora, uma freira, uma cantora de cabaret, uma santa e uma prostituta&quot;,disse a cantora. Influenciada criativamente por morar em Lisboa ao longo dos &uacute;ltimos anos, &quot;MADAME X&quot; &eacute; uma cole&ccedil;&atilde;o de m&uacute;sicas in&eacute;ditas que celebram a paix&atilde;o de longa data de Madonna pela m&uacute;sica e cultura latina, assim como outras influ&ecirc;ncias globais. Gravado ao longo de 18 meses em Portugal, Londres, Nova Iorque e Los Angeles, Madonna colaborou em &quot;MADAME X&quot;com o produtor de longa data Mirwais, al&eacute;m de Mike Dean, Diplo, entre outros.</p><p>Repert&oacute;rio dos LPs: LP 1 / A 1. Medellin with maluma 2. Dark ballet 3. God control 4. Future ft. quavo LP 1 / B 5. Batuka 6. Killers who are partying 7. Crave ft. swae lee LP 2 / C 8. Crazy 9. Come alive 10. Extreme Occident 11. Faz gostoso ft. anitta LP 2 / D 12. Bitch i&#39;m loca ft. maluma 13. I don&#39;t search i find 14. Looking for Mercy 15. I rise</p>');
